### ISSUE TITLE
webpack.config.js moved but original location still referenced in blog post

### ISSUE THREAD

**Issue by donalhunt** [fceruti/django-starter-project#4]
Blog post: https://dev.to/fceruti/setting-up-a-django-project-like-a-pro-353

original location: https://github.com/fceruti/django-starter-project/blob/master/webpack.config.js
new location: https://github.com/fceruti/django-starter-project/blob/master/assets/webpack.config

**Comment by fceruti** [comment]
Thanks for the heads up!
